name: revruns
channels:
  - nrel
  - conda-forge
  - defaults
dependencies:
  - colorama
  - descartes
  - gdal
  - geopandas=0.11.1
  - h5py
  - ipython
  - numpy
  - pandas
  - python=3.9
  - rasterio
  - rioxarray
  - tabulate
  - tqdm
  - xarray
  - xlrd
  - xlsxwriter
  - pip
  - pip:
    - addfips
    - cpi
    - HOPP==0.0.5
    - h5pyd
    - ipywidgets
    - openpyxl
    - pgpasslib
    - pathos
    - pandarallel
    - pathos
    - us
